---

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: "{{ kubernetes_gpg_key_url }}"
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: "{{ kubernetes_apt_repo }}"
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries (kubelet, kubeadm, kubectl)
  apt:
    name:
      - "kubelet={{ kubernetes_version }}"
      - "kubeadm={{ kubernetes_version }}"
      - "kubectl={{ kubernetes_version }}"
    state: present
    update_cache: yes
  notify:
    - kubeadm status
