---

- name: Setup kubernetes cluster with kubeadm
  hosts: all
  become: true
  roles:
    - swap-disable
    - docker
    - kubeadm

- name: Check if cluster is already initialized and register output as variable
  hosts: master
  become: true
  roles:
    - kubeadm-status
  tags: config-master

- name: Initialize kubeadm master
  hosts: master
  become: true
  roles:
    - { role: kubeadm-master, when: cluster_status is failed }
  tags: config-master
