---

- name: Install Kubernetes and dependencies
  hosts: all
  become: true
  roles:
    - swap-disable
    - docker
    - kubeadm

- name: Check if cluster is already initialized and register output as variable
  hosts: master
  become: true
  roles:
    - cluster-initialized-check
  tags: config-master

- name: Initialize the Kubernetes cluster on master node using kubeadm (only if the cluster is not already initialized)
  hosts: master
  become: true
  roles:
    - { role: kubeadm-master-init, when: cluster_initialized is failed }
  tags: config-master

- name: Generate command for joining the worker nodes to the Kubernetes cluster
  hosts: master
  become: true
  roles:
    - kubeadm-get-join-command
  tags: config-workers

- name: Join the Kubernetes cluster with the worker nodes
  hosts: workers
  become: true
  roles:
    - kubeadm-worker-join
  tags: config-workers
