---

- name: Install Kubernetes and dependencies
  hosts: all
  become: true
  roles:
    - swap-disable
    - docker
    - kubeadm

- name: Check if cluster is already initialized and register output as variable
  hosts: master
  become: true
  roles:
    - cluster-initialized-check
  tags: config-master

- name: Initialize the Kubernetes cluster on master node using kubeadm (only if the cluster is not already initialized)
  hosts: master
  become: true
  roles:
    - { role: kubeadm-master, when: cluster_initialized is failed }
  tags: config-master
