---

- name: Copy the join command to server location
  copy:
    src: "{{ join_command_local_path }}"
    dest: /tmp/join-command.sh
    mode: 0777

- name: Join the node to cluster
  command: sh /tmp/join-command.sh
