apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: result-app-deployment-label

spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-app-pod-label
  template:
    metadata:
      name: result-app-pod
      labels:
        app: result-app-pod-label
    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
