---

- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
    state: present
    update_cache: yes

- name: Add an apt signing key for Docker (Add Docker’s official GPG key)
  apt_key:
    url: "{{ docker_gpg_key_url }}"
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present

- name: Install specific version of Docker
  apt:
    name: "docker-ce={{ docker_ce_version }}"
    state: present
    update_cache: yes

- name: Add Vagrant user to Docker group
  user:
    name: vagrant
    group: docker
  notify:
    - docker status
